name: Build docker image

on: workflow_call

jobs:
  tests:
    name: Build and push docker image
    runs-on: ubuntu-latest
    # On GitHub create an environment filled with the data
    environment: Dockerhub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build docker image
        run: ./gradlew jib -Pflutter
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          DOCKER_USR: ${{ vars.DOCKER_USR }}
          DOCKER_PSW: ${{ secrets.DOCKER_PSW }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
