name: run-tests

on:
  push:
    branches:
      - develop

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  buildDocker:
    needs:
      - tests
    uses: ./.github/workflows/build-docker.yml

