name: run-tests

on:
  push:
    tags:
      - v*


jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  buildDocker:
    needs:
      - tests
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit

