name: Master Build

on:
  push:
    branches:
      - master


jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  buildDocker:
    needs:
      - tests
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
