name: Master Build

on:
  push:
    branches:
      - master


jobs:
  #  tests:
  #    uses: ./.github/workflows/run-tests.yml
  #    secrets: inherit

  buildDocker:
    #    needs:
    #      - tests
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    #    needs:
    #      - tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Prepare release artifacts
        run: ./gradlew prepareReleaseArtifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          append_body: false
          files: |
            build/**




