name: run-tests

on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          [
            server,
            app,
            common-test
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Run test ${{matrix.module}}
        run: ./gradlew ${{matrix.module}}:test

      - name: Run test ${{matrix.module}}
        run: ./gradlew ${{matrix.module}}:integrationTest

      - name: Run test ${{matrix.module}}
        run: ./gradlew ${{matrix.module}}:checkFormat
