name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The version with which the code should be released on master'
        type: string
        required: true
      new-snapshot-version:
        description: 'The next snapshot version for master'
        type: string
        required: true


jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  trigger-release:
    runs-on: ubuntu-latest
    name: Trigger the release
    needs:
      - tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Configure Git
        run: |
          git config --global user.name 'Release Action'
          git config --global user.email 'release@noreply.github.com'

      - name: Set version to ${{ github.event.inputs.release-version }}
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: version.properties
          write-mode: overwrite
          contents: |
            version=${{ github.event.inputs.release-version }}

      - name: Commit release version
        run: git commit -a -m "Bump version to ${{ github.event.inputs.release-version }}"

      - name: Tag release commit
        run: git tag v${{ github.event.inputs.release-version }} HEAD

      - name: Push release commit
        run: git push --atomic origin HEAD v${{ github.event.inputs.release-version }}

      - name: Set version to ${{ github.event.inputs.new-snapshot-version }}
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: version.properties
          write-mode: overwrite
          contents: |
            version=${{ github.event.inputs.new-snapshot-version }}

      - name: Commit new snapshot version
        run: git commit -a -m "Bump version to ${{ github.event.inputs.new-snapshot-version }}"

      - name: Push new snapshot version commit
        run: git push origin HEAD

